// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStateJSON() {
  return window['go']['main']['App']['GetStateJSON']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
