// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1) {
  return window['go']['main']['App']['AddTorrent'](arg1);
}

export function GetDevTorrent() {
  return window['go']['main']['App']['GetDevTorrent']();
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RemoveTorrent(arg1) {
  return window['go']['main']['App']['RemoveTorrent'](arg1);
}
