// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetDevTorrent():Promise<backend.Torrent>;

export function OpenFileDialog():Promise<backend.Torrent>;
